### ISSUE TITLE
Looping Yellow Stage => Quantizer

### ISSUE THREAD

**Issue by jb0000** [qiemem/eurorack#1]
Hello,

thank you for this awesome firmware!

Here a suggestion for the looping standalone step (yellow) mode:
Swap the slew function for a simple quantizer. 3 scales could be selected with the knob:

- Chromatic
- Major
- Minor

The slider value and cv would be continuously quantized in normal mode and sampled at every gate in gated mode.
Bonus points for more scales such as pentatonic for example.
Stages hardware should be could enough to allow exact pitch voltages.

It would be an awesome feature since small quantizers are not that widespread in eurorack and it would just pair so nicely with your Turing Machine and random modes.

Edit: I just realized that looping standalone gated step mode is already used for T&H. Maybe T&H could be set via button + slider but its not as clean as I hoped. Also octaves and octaves + fifths would be fun scales.

**Comment by qiemem** [comment]
Hey! Sorry for the delayed response. At first, I had been thinking that quantization was beyond the scope of what Stages should do, especially since the UI for it would be pretty tough. That said, I managed to figure out a UI that seems to work pretty well.

Yellow segments (all yellow segments) now let you set scale by holding the button and moving the slider. The available scales, in order of slider position (from top), are:

- None
- Chromatic
- Major
- Pentatonic

Once quantization is applied, the slider will then offset across two octaves. Thus, to access other modes, you just move the slider to the corresponding tonic. So, the bottom half of the slider gives you (again, in order):

- Locrian
- Aeolian (minor)
- Mixolydian
- Lydian
- Phrygian
- Dorian
- Ionian (major)

The top half of the slider gives you the same thing, but an octave up. To get to minor in particular, I've just been starting at the bottom, and counting notes as I move the slider up ("C, D, E, F, G, A")...

Maybe slightly clunky, but the nice thing about this is that it makes it very easy to select basic scale, and then possible (without too much trouble) to select an arbitrary mode despite the UI limitations. Furthermore, it also gives you a quite playable quantized sequencer.

A couple downsides:
- There is no UI indication of which scale you're in except when you're switching (when you're switching, it changes LED color to reflect scale).
- You have to set root with your VCO's tune instead of having a dedicated root parameter. 

As I mentioned, this will work for *all* yellow segments: so a non-gated looping segment gives you a quantizable slew. Gated for quantizable S&H. In group yellows gives you a quantized sequencer.

What do you think?

Implemented in c430c502da4b246950c2fd9460c678ca1d159e42

**Comment by jb0000** [comment]
🤯 Awesome!
You took it to another level. 
I will test it as soon as possible.

**Comment by jb0000** [comment]
Some thoughts after testing:

- It is really fun to use and opens up a lot of patching opportunities
- Slew after quantizing is great
- The LED color change while selecting a scale is really helpful

What could be improved:

- Disable the fader while selecting a scale. It would be lovely to hear the effect of different scales on the current CV signal but since the offset is ever changing while selecting, it is hard to hear the differences. Also it can produce some unpleasant high frequency tones when selecting the scale at the top with the fader and when the melody is already in the upper registers. After releasing the knob there would be a disconnect between fader position and offset. One could jump the offset to the fader position or catch the offset with the fader(prefered). There is also the MI magic trick (like the blend knob on Clouds) but that is probably too much work.

- Inverse scale order. My default position for the fader in the yellow stage is in the bottom. That let me to expected the scales to be in the inverse order. It would be great to get a few opinions on that since it seems to depend on personal preference.

Overall its really great and I will continue testing it.

**Comment by qiemem** [comment]
This is fantastic feedback! Thank you!

> Disable the fader while selecting a scale.

Good call. This has been bugging me too.

> One could jump the offset to the fader position or catch the offset with the fader(prefered).

What do you mean by catch the offset?

> Inverse scale order.

Makes sense. I had been thinking higher = more notes (for some reason, I thought Marbles worked like this... but it's definitely the opposite), but the bottom = default is probably a more important consideration.

**Comment by qiemem** [comment]
Flipped the scale order in f389936d7ac473c08803eb78e4fddb923dc5ca9c and locked pot and slider values when changing parameters in 2eff9aa89b207b9eedf4657d3a950a5a260e2cb9.

Right now, it jumps to the current slider/pot value when you release the button, but I'm definitely interested in other methods.

Thanks again for testing and the feedback!

**Comment by jb0000** [comment]
Wow you are fast!

> What do you mean by catch the offset?

I found a nice description here with pictures here:
[Minilouge manual page 43](https://cdn.korg.com/us/support/download/files/23be1d77cac2c42e6f6c586cf0f75ffb.pdf?response-content-disposition=inline%3Bfilename%3Dminilogue_OM_E3.pdf&response-content-type=application%2Fpdf%3B)
<details>
<summary>Excerpt</summary>

- **Jump**: When you turn the knob, the parameter value will jump to the value indicated by the knob. Since this makes it easy to hear the results while editing, we recommend that you use this setting.
- **Catch**: Turning the knob will not change the parameter value until the knob position matches the stored value. We recommend that you use this setting when you don’t want the sound to change abruptly, such as while performing. 
- **Scale**: When you turn the knob, the parameter value will increase or decrease in
a relative manner in the direction that it is turned. When you turn the knob and it reaches the full extent of its motion, it will operate proportionate to the maximum or minimum value of the parameter. Once the knob position matches the param- eter value, the knob position and parameter value will subsequently be linked.</details >

**Comment by qiemem** [comment]
This is a great reference, thanks!

I implemented the catch mechanism, and it feels a little odd to be honest. It's hard to indicate when the value doesn't match the position. I set it so that the slider led/segment type led would blink rapidly when there's a mismatch, but that can be pretty hard to distinguish from other led states.

Similarly, with the scale mechanism (which I assume is similar to Clouds' blend knob), there's no way to indicate the true value of the thing, meaning that you can't tell by looking what state the module is in (though I suppose that's already true with quantization).

What if the value automatically goes to the position of the slider, but at a slower rate (e.g. a couple v/s)? That would ensure there were no abrupt changes, but also makes sure that values can't persistently be off from positions.

**Comment by jb0000** [comment]
I can see how it is akward. Inspite of all the added function Stages still is a module where you can see what’s going on at first glance. That would be lost with catch or scale. 
After spending some more time I found that the jump is not a big issue with medium to slowly gated s/hs because you can adjust in between the gates. I will test somemore with continues quantization. 
The slowly rising catch might be very nice. Another idea would be to give a 1 seconds latency and then jump.

**Comment by qiemem** [comment]
Moved discussion of value/position agreement to #6 as it's more general than quantization. Closing as this seems to be working well!
