### ISSUE TITLE
Random segment pot step range off by one

### ISSUE THREAD

**Issue by Lokua** [qiemem/eurorack#10]
On v1.0.0-beta4 as well as v1.0.0 the random segment generator pot goes from 1-15, not 16.
I have reproduced on more than one channel to make sure it isn't a hardware issue.

**Comment by qiemem** [comment]
Thanks for the report! In one of my cases, I think the pot reads a little high, as I was getting 16, but just tried it in another case, and it does indeed max out at 15. Easy enough to fix though.

On the topic, I had been considering changing the available lengths to be the same as in the actual Turing Machine module (2,3,4,5,6,8,12,16), rather than the current 1...16, to make it a little easier to dial in common lengths. What do you think?

**Comment by Lokua** [comment]
The lengths are admittedly hard to dial in so I can't argue with the improvement that would make for the more common use cases, but that's a tough call. I surely wouldn't want to loose 7.

Edit: maybe crowdsource via poll in muffs?

**Comment by qiemem** [comment]
Cool, thanks for the feedback. I think I'll just leave it as is for the moment to get this bug fix release out and then solicit feedback. Thanks again for the report!
